name_id = {'brown mushroom': 'BROWN_MUSHROOM', 'cocoa beans': 'INK_SACK:3', 'lapis lazuli': 'INK_SACK:4', 'spooky shard': 'SPOOKY_SHARD', 'tarantula web': 'TARANTULA_WEB', 'carrot': 'CARROT_ITEM', 'enchanted potato': 'ENCHANTED_POTATO', 'experience bottle': 'EXP_BOTTLE', 'green jerry box': 'JERRY_BOX_GREEN', 'enchanted slimeball': 'ENCHANTED_SLIME_BALL', 'enchanted red mushroom': 'ENCHANTED_RED_MUSHROOM', 'enchanted golden carrot': 'ENCHANTED_GOLDEN_CARROT', 'enchanted rabbit hide': 'ENCHANTED_RABBIT_HIDE', 'enchanted birch wood': 'ENCHANTED_BIRCH_LOG', 'enchanted gunpowder': 'ENCHANTED_GUNPOWDER', 'enchanted melon': 'ENCHANTED_MELON', 'enchanted sugar': 'ENCHANTED_SUGAR', 'cactus': 'CACTUS', 'enchanted blaze rod': 'ENCHANTED_BLAZE_ROD', 'enchanted cake': 'ENCHANTED_CAKE', 'pumpkin': 'PUMPKIN', 'enchanted brown mushroom': 'ENCHANTED_BROWN_MUSHROOM', 'nurse shark tooth': 'NURSE_SHARK_TOOTH', 'wheat': 'WHEAT', 'enchanted raw salmon': 'ENCHANTED_RAW_SALMON', 'enchanted glistering melon': 'ENCHANTED_GLISTERING_MELON', 'prismarine shard': 'PRISMARINE_SHARD', 'protector dragon fragment': 'PROTECTOR_FRAGMENT', 'enchanted emerald': 'ENCHANTED_EMERALD', 'enchanted spider eye': 'ENCHANTED_SPIDER_EYE', 'red mushroom': 'RED_MUSHROOM', 'grand experience bottle': 'GRAND_EXP_BOTTLE', 'mutton': 'MUTTON', 'enchanted melon block': 'ENCHANTED_MELON_BLOCK', 'shark fin': 'SHARK_FIN', 'diamond': 'DIAMOND', 'wise dragon fragment': 'WISE_FRAGMENT', 'cobblestone': 'COBBLESTONE', 'refined mithril': 'REFINED_MITHRIL', 'spider eye': 'SPIDER_EYE', 'raw fish': 'RAW_FISH', 'enchanted pufferfish': 'ENCHANTED_PUFFERFISH', 'potato': 'POTATO_ITEM', 'enchanted brown mushroom block': 'ENCHANTED_HUGE_MUSHROOM_1', 'refined diamond': 'REFINED_DIAMOND', 'enchanted cobblestone': 'ENCHANTED_COBBLESTONE', 'tightly-tied hay bale': 'TIGHTLY_TIED_HAY_BALE', 'enchanted red mushroom block': 'ENCHANTED_HUGE_MUSHROOM_2', 'ice bait': 'ICE_BAIT', 'raw porkchop': 'PORK', 'prismarine crystals': 'PRISMARINE_CRYSTALS', 'ice': 'ICE', 'tiger shark tooth': 'TIGER_SHARK_TOOTH', 'brown mushroom block': 'HUGE_MUSHROOM_1', 'red mushroom block': 'HUGE_MUSHROOM_2', 'dark oak wood': 'LOG_2:1', 'enchanted snow block': 'ENCHANTED_SNOW_BLOCK', 'golden tooth': 'GOLDEN_TOOTH', 'hyper catalyst': 'HYPER_CATALYST', 'string': 'STRING', "rabbit's foot": 'RABBIT_FOOT', 'redstone': 'REDSTONE', 'golden jerry box': 'JERRY_BOX_GOLDEN', 'pumpkin guts': 'PUMPKIN_GUTS', 'enchanted cactus green': 'ENCHANTED_CACTUS_GREEN', 'booster cookie': 'BOOSTER_COOKIE', 'was temporarily: enchanted carrot on a stick': 'ENCHANTED_CARROT_ON_A_STICK', 'enchanted lapis block': 'ENCHANTED_LAPIS_LAZULI_BLOCK', 'enchanted end stone': 'ENCHANTED_ENDSTONE', 'enchanted cookie': 'ENCHANTED_COOKIE', 'enchanted sand': 'ENCHANTED_SAND', 'colossal experience bottle': 'COLOSSAL_EXP_BOTTLE', 'enchanted string': 'ENCHANTED_STRING', 'strong dragon fragment': 'STRONG_FRAGMENT', 'slimeball': 'SLIME_BALL', 'snowball': 'SNOW_BALL', 'holy dragon fragment': 'HOLY_FRAGMENT', 'enchanted acacia wood': 'ENCHANTED_ACACIA_LOG', 'enchanted egg': 'ENCHANTED_EGG', 'sand': 'SAND', 'soul fragment': 'SOUL_FRAGMENT', 'raw chicken': 'RAW_CHICKEN', 'ancient claw': 'ANCIENT_CLAW', 'enchanted lapis lazuli': 'ENCHANTED_LAPIS_LAZULI', 'enchanted ghast tear': 'ENCHANTED_GHAST_TEAR', 'enchanted cocoa bean': 'ENCHANTED_COCOA', 'carrot bait': 'CARROT_BAIT', 'seeds': 'SEEDS', 'enchanted leather': 'ENCHANTED_LEATHER', 'enchanted shark fin': 'ENCHANTED_SHARK_FIN', 'enchanted sponge': 'ENCHANTED_SPONGE', 'hay bale': 'HAY_BLOCK', 'flint': 'FLINT', 'ink sack': 'INK_SACK', 'enchanted rotten flesh': 'ENCHANTED_ROTTEN_FLESH', 'wolf tooth': 'WOLF_TOOTH', 'enchanted spruce wood': 'ENCHANTED_SPRUCE_LOG', 'enchanted grilled pork': 'ENCHANTED_GRILLED_PORK', 'enchanted nether wart': 'ENCHANTED_NETHER_STALK', 'enchanted redstone block': 'ENCHANTED_REDSTONE_BLOCK', 'enchanted quartz block': 'ENCHANTED_QUARTZ_BLOCK', 'enchanted ancient claw': 'ENCHANTED_ANCIENT_CLAW', 'green candy': 'GREEN_CANDY', 'enchanted redstone': 'ENCHANTED_REDSTONE', 'enchanted redstone lamp': 'ENCHANTED_REDSTONE_LAMP', 'great white shark tooth': 'GREAT_WHITE_SHARK_TOOTH', 'gravel': 'GRAVEL', 'melon': 'MELON', 'enchanted lava bucket': 'ENCHANTED_LAVA_BUCKET', 'enchanted packed ice': 'ENCHANTED_PACKED_ICE', 'pufferfish': 'RAW_FISH:3', 'enchanted prismarine shard': 'ENCHANTED_PRISMARINE_SHARD', 'recombobulator 3000': 'RECOMBOBULATOR_3000', 'enchanted iron block': 'ENCHANTED_IRON_BLOCK', 'enchanted carrot on a stick': 'ENCHANTED_CARROT_STICK', 'bone': 'BONE', 'clownfish': 'RAW_FISH:2', 'raw salmon': 'RAW_FISH:1', 'revenant flesh': 'REVENANT_FLESH', 'enchanted glowstone': 'ENCHANTED_GLOWSTONE', 'enchanted pork': 'ENCHANTED_PORK', 'feather': 'FEATHER', 'netherrack': 'NETHERRACK', 'whale bait': 'WHALE_BAIT', 'sponge': 'SPONGE', 'blaze rod': 'BLAZE_ROD', 'enchanted dark oak wood': 'ENCHANTED_DARK_OAK_LOG', 'young dragon fragment': 'YOUNG_FRAGMENT', 'enchanted clownfish': 'ENCHANTED_CLOWNFISH', 'refined mineral': 'REFINED_MINERAL', 'enchanted gold': 'ENCHANTED_GOLD', 'enchanted raw chicken': 'ENCHANTED_RAW_CHICKEN', 'enchanted lily pad': 'ENCHANTED_WATER_LILY', 'spruce wood': 'LOG:1', 'titanium': 'TITANIUM_ORE', 'blue shark tooth': 'BLUE_SHARK_TOOTH', 'catalyst': 'CATALYST', 'jungle wood': 'LOG:3', 'birch wood': 'LOG:2', 'blessed bait': 'BLESSED_BAIT', 'enchanted glowstone dust': 'ENCHANTED_GLOWSTONE_DUST', 'enchanted ink sack': 'ENCHANTED_INK_SACK', 'enchanted cactus': 'ENCHANTED_CACTUS', 'enchanted sugar cane': 'ENCHANTED_SUGAR_CANE', 'enchanted cooked salmon': 'ENCHANTED_COOKED_SALMON', 'enchanted seeds': 'ENCHANTED_SEEDS', 'oak wood': 'LOG', "jacob's ticket": 'JACOBS_TICKET', 'enchanted bone block': 'ENCHANTED_BONE_BLOCK', 'ghast tear': 'GHAST_TEAR', 'unstable dragon fragment': 'UNSTABLE_FRAGMENT', 'enchanted ender pearl': 'ENCHANTED_ENDER_PEARL', 'purple candy': 'PURPLE_CANDY', 'enchanted fermented spider eye': 'ENCHANTED_FERMENTED_SPIDER_EYE', 'polished pumpkin': 'POLISHED_PUMPKIN', 'spiked bait': 'SPIKED_BAIT', 'enchanted gold block': 'ENCHANTED_GOLD_BLOCK', 'enchanted jungle wood': 'ENCHANTED_JUNGLE_LOG', 'enchanted flint': 'ENCHANTED_FLINT', 'iron ingot': 'IRON_INGOT', 'enchanted emerald block': 'ENCHANTED_EMERALD_BLOCK', 'enchanted clay': 'ENCHANTED_CLAY_BALL', 'glowstone dust': 'GLOWSTONE_DUST', 'gold ingot': 'GOLD_INGOT', 'revenant viscera': 'REVENANT_VISCERA', 'tarantula silk': 'TARANTULA_SILK', 'titanic experience bottle': 'TITANIC_EXP_BOTTLE', 'enchanted mutton': 'ENCHANTED_MUTTON', 'super compactor 3000': 'SUPER_COMPACTOR_3000', 'super enchanted egg': 'SUPER_EGG', 'enchanted iron': 'ENCHANTED_IRON', 'stock of stonks': 'STOCK_OF_STONKS', 'mithril': 'MITHRIL_ORE', 'enchanted hay bale': 'ENCHANTED_HAY_BLOCK', 'enchanted paper': 'ENCHANTED_PAPER', 'enchanted titanium': 'ENCHANTED_TITANIUM', 'enchanted bone': 'ENCHANTED_BONE', 'enchanted diamond block': 'ENCHANTED_DIAMOND_BLOCK', 'spooky bait': 'SPOOKY_BAIT', 'superior dragon fragment': 'SUPERIOR_FRAGMENT', 'emerald': 'EMERALD', 'enchanted rabbit foot': 'ENCHANTED_RABBIT_FOOT', 'light bait': 'LIGHT_BAIT', 'hot potato book': 'HOT_POTATO_BOOK', 'enchanted ice': 'ENCHANTED_ICE', 'clay': 'CLAY_BALL', 'old dragon fragment': 'OLD_FRAGMENT', 'green gift': 'GREEN_GIFT', 'packed ice': 'PACKED_ICE', 'lily pad': 'WATER_LILY', 'acacia wood': 'LOG_2', 'hamster wheel': 'HAMSTER_WHEEL', 'enchanted obsidian': 'ENCHANTED_OBSIDIAN', 'enchanted coal': 'ENCHANTED_COAL', 'enchanted quartz': 'ENCHANTED_QUARTZ', 'coal': 'COAL', 'ender pearl': 'ENDER_PEARL', 'enchanted block of coal': 'ENCHANTED_COAL_BLOCK', 'werewolf skin': 'WEREWOLF_SKIN', 'enchanted prismarine crystals': 'ENCHANTED_PRISMARINE_CRYSTALS', 'daedalus stick': 'DAEDALUS_STICK', 'enchanted wet sponge': 'ENCHANTED_WET_SPONGE', 'enchanted raw fish': 'ENCHANTED_RAW_FISH', 'end stone': 'ENDER_STONE', 'nether quartz': 'QUARTZ', 'foul flesh': 'FOUL_FLESH', 'raw beef': 'RAW_BEEF', 'purple jerry box': 'JERRY_BOX_PURPLE', 'enchanted eye of ender': 'ENCHANTED_EYE_OF_ENDER', 'ectoplasm': 'ECTOPLASM', 'sugar cane': 'SUGAR_CANE', 'magma cream': 'MAGMA_CREAM', 'shark bait': 'SHARK_BAIT', 'red gift': 'RED_GIFT', 'enchanted mithril': 'ENCHANTED_MITHRIL', 'blue jerry box': 'JERRY_BOX_BLUE', 'enchanted raw beef': 'ENCHANTED_RAW_BEEF', 'enchanted feather': 'ENCHANTED_FEATHER', 'enchanted slime block': 'ENCHANTED_SLIME_BLOCK', 'enchanted oak wood': 'ENCHANTED_OAK_LOG', 'rabbit hide': 'RABBIT_HIDE', 'white gift': 'WHITE_GIFT', 'raw rabbit': 'RABBIT', 'gunpowder': 'SULPHUR', 'dark bait': 'DARK_BAIT', 'nether wart': 'NETHER_STALK', 'enchanted carrot': 'ENCHANTED_CARROT', 'enchanted pumpkin': 'ENCHANTED_PUMPKIN', 'griffin feather': 'GRIFFIN_FEATHER', 'rotten flesh': 'ROTTEN_FLESH', 'enchanted cooked fish': 'ENCHANTED_COOKED_FISH', 'obsidian': 'OBSIDIAN', 'minnow bait': 'MINNOW_BAIT', 'enchanted magma cream': 'ENCHANTED_MAGMA_CREAM', 'enchanted firework rocket': 'ENCHANTED_FIREWORK_ROCKET', 'starfall': 'STARFALL', 'leather': 'LEATHER', 'enchanted cooked mutton': 'ENCHANTED_COOKED_MUTTON', 'refined titanium': 'REFINED_TITANIUM', 'enchanted raw rabbit': 'ENCHANTED_RABBIT', 'mutant nether wart': 'MUTANT_NETHER_STALK', 'enchanted bread': 'ENCHANTED_BREAD', 'fuming potato book': 'FUMING_POTATO_BOOK', 'enchanted charcoal': 'ENCHANTED_CHARCOAL', 'enchanted blaze powder': 'ENCHANTED_BLAZE_POWDER', 'summoning eye': 'SUMMONING_EYE', 'fish bait': 'FISH_BAIT', 'snow block': 'SNOW_BLOCK', 'enchanted baked potato': 'ENCHANTED_BAKED_POTATO', 'compactor': 'COMPACTOR', 'enchanted diamond': 'ENCHANTED_DIAMOND'}
id_name = {
    "BROWN_MUSHROOM": "Brown Mushroom",
    "INK_SACK:3": "Cocoa Beans",
    "INK_SACK:4": "Lapis Lazuli",
    "SPOOKY_SHARD": "Spooky Shard",
    "TARANTULA_WEB": "Tarantula Web",
    "CARROT_ITEM": "Carrot",
    "ENCHANTED_POTATO": "Enchanted Potato",
    "EXP_BOTTLE": "Experience Bottle",
    "JERRY_BOX_GREEN": "Green Jerry Box",
    "ENCHANTED_SLIME_BALL": "Enchanted Slimeball",
    "ENCHANTED_RED_MUSHROOM": "Enchanted Red Mushroom",
    "ENCHANTED_GOLDEN_CARROT": "Enchanted Golden Carrot",
    "ENCHANTED_RABBIT_HIDE": "Enchanted Rabbit Hide",
    "ENCHANTED_BIRCH_LOG": "Enchanted Birch Wood",
    "ENCHANTED_GUNPOWDER": "Enchanted Gunpowder",
    "ENCHANTED_MELON": "Enchanted Melon",
    "ENCHANTED_SUGAR": "Enchanted Sugar",
    "CACTUS": "Cactus",
    "ENCHANTED_BLAZE_ROD": "Enchanted Blaze Rod",
    "ENCHANTED_CAKE": "Enchanted Cake",
    "PUMPKIN": "Pumpkin",
    "ENCHANTED_BROWN_MUSHROOM": "Enchanted Brown Mushroom",
    "NURSE_SHARK_TOOTH": "Nurse Shark Tooth",
    "WHEAT": "Wheat",
    "ENCHANTED_RAW_SALMON": "Enchanted Raw Salmon",
    "ENCHANTED_GLISTERING_MELON": "Enchanted Glistering Melon",
    "PRISMARINE_SHARD": "Prismarine Shard",
    "PROTECTOR_FRAGMENT": "Protector Dragon Fragment",
    "ENCHANTED_EMERALD": "Enchanted Emerald",
    "ENCHANTED_SPIDER_EYE": "Enchanted Spider Eye",
    "RED_MUSHROOM": "Red Mushroom",
    "GRAND_EXP_BOTTLE": "Grand Experience Bottle",
    "MUTTON": "Mutton",
    "ENCHANTED_MELON_BLOCK": "Enchanted Melon Block",
    "SHARK_FIN": "Shark Fin",
    "DIAMOND": "Diamond",
    "WISE_FRAGMENT": "Wise Dragon Fragment",
    "COBBLESTONE": "Cobblestone",
    "REFINED_MITHRIL": "Refined Mithril",
    "SPIDER_EYE": "Spider Eye",
    "RAW_FISH": "Raw Fish",
    "ENCHANTED_PUFFERFISH": "Enchanted Pufferfish",
    "POTATO_ITEM": "Potato",
    "ENCHANTED_HUGE_MUSHROOM_1": "Enchanted Brown Mushroom Block",
    "REFINED_DIAMOND": "Refined Diamond",
    "ENCHANTED_COBBLESTONE": "Enchanted Cobblestone",
    "TIGHTLY_TIED_HAY_BALE": "Tightly-Tied Hay Bale",
    "ENCHANTED_HUGE_MUSHROOM_2": "Enchanted Red Mushroom Block",
    "ICE_BAIT": "Ice Bait",
    "PORK": "Raw Porkchop",
    "PRISMARINE_CRYSTALS": "Prismarine Crystals",
    "ICE": "Ice",
    "TIGER_SHARK_TOOTH": "Tiger Shark Tooth",
    "HUGE_MUSHROOM_1": "Brown Mushroom Block",
    "HUGE_MUSHROOM_2": "Red Mushroom Block",
    "LOG_2:1": "Dark Oak Wood",
    "ENCHANTED_SNOW_BLOCK": "Enchanted Snow Block",
    "GOLDEN_TOOTH": "Golden Tooth",
    "HYPER_CATALYST": "Hyper Catalyst",
    "STRING": "String",
    "RABBIT_FOOT": "Rabbit's Foot",
    "REDSTONE": "Redstone",
    "JERRY_BOX_GOLDEN": "Golden Jerry Box",
    "PUMPKIN_GUTS": "Pumpkin Guts",
    "ENCHANTED_CACTUS_GREEN": "Enchanted Cactus Green",
    "BOOSTER_COOKIE": "Booster Cookie",
    "ENCHANTED_CARROT_ON_A_STICK": "Was Temporarily: Enchanted Carrot on a Stick",
    "ENCHANTED_LAPIS_LAZULI_BLOCK": "Enchanted Lapis Block",
    "ENCHANTED_ENDSTONE": "Enchanted End Stone",
    "ENCHANTED_COOKIE": "Enchanted Cookie",
    "ENCHANTED_SAND": "Enchanted Sand",
    "COLOSSAL_EXP_BOTTLE": "Colossal Experience Bottle",
    "ENCHANTED_STRING": "Enchanted String",
    "STRONG_FRAGMENT": "Strong Dragon Fragment",
    "SLIME_BALL": "Slimeball",
    "SNOW_BALL": "Snowball",
    "HOLY_FRAGMENT": "Holy Dragon Fragment",
    "ENCHANTED_ACACIA_LOG": "Enchanted Acacia Wood",
    "ENCHANTED_EGG": "Enchanted Egg",
    "SAND": "Sand",
    "SOUL_FRAGMENT": "Soul Fragment",
    "RAW_CHICKEN": "Raw Chicken",
    "ANCIENT_CLAW": "Ancient Claw",
    "ENCHANTED_LAPIS_LAZULI": "Enchanted Lapis Lazuli",
    "ENCHANTED_GHAST_TEAR": "Enchanted Ghast Tear",
    "ENCHANTED_COCOA": "Enchanted Cocoa Bean",
    "CARROT_BAIT": "Carrot Bait",
    "SEEDS": "Seeds",
    "ENCHANTED_LEATHER": "Enchanted Leather",
    "ENCHANTED_SHARK_FIN": "Enchanted Shark Fin",
    "ENCHANTED_SPONGE": "Enchanted Sponge",
    "HAY_BLOCK": "Hay Bale",
    "FLINT": "Flint",
    "INK_SACK": "Ink Sack",
    "ENCHANTED_ROTTEN_FLESH": "Enchanted Rotten Flesh",
    "WOLF_TOOTH": "Wolf Tooth",
    "ENCHANTED_SPRUCE_LOG": "Enchanted Spruce Wood",
    "ENCHANTED_GRILLED_PORK": "Enchanted Grilled Pork",
    "ENCHANTED_NETHER_STALK": "Enchanted Nether Wart",
    "ENCHANTED_REDSTONE_BLOCK": "Enchanted Redstone Block",
    "ENCHANTED_QUARTZ_BLOCK": "Enchanted Quartz Block",
    "ENCHANTED_ANCIENT_CLAW": "Enchanted Ancient Claw",
    "GREEN_CANDY": "Green Candy",
    "ENCHANTED_REDSTONE": "Enchanted Redstone",
    "ENCHANTED_REDSTONE_LAMP": "Enchanted Redstone Lamp",
    "GREAT_WHITE_SHARK_TOOTH": "Great White Shark Tooth",
    "GRAVEL": "Gravel",
    "MELON": "Melon",
    "ENCHANTED_LAVA_BUCKET": "Enchanted Lava Bucket",
    "ENCHANTED_PACKED_ICE": "Enchanted Packed Ice",
    "RAW_FISH:3": "Pufferfish",
    "ENCHANTED_PRISMARINE_SHARD": "Enchanted Prismarine Shard",
    "RECOMBOBULATOR_3000": "Recombobulator 3000",
    "ENCHANTED_IRON_BLOCK": "Enchanted Iron Block",
    "ENCHANTED_CARROT_STICK": "Enchanted Carrot on a Stick",
    "BONE": "Bone",
    "RAW_FISH:2": "Clownfish",
    "RAW_FISH:1": "Raw Salmon",
    "REVENANT_FLESH": "Revenant Flesh",
    "ENCHANTED_GLOWSTONE": "Enchanted Glowstone",
    "ENCHANTED_PORK": "Enchanted Pork",
    "FEATHER": "Feather",
    "NETHERRACK": "Netherrack",
    "WHALE_BAIT": "Whale Bait",
    "SPONGE": "Sponge",
    "BLAZE_ROD": "Blaze Rod",
    "ENCHANTED_DARK_OAK_LOG": "Enchanted Dark Oak Wood",
    "YOUNG_FRAGMENT": "Young Dragon Fragment",
    "ENCHANTED_CLOWNFISH": "Enchanted Clownfish",
    "REFINED_MINERAL": "Refined Mineral",
    "ENCHANTED_GOLD": "Enchanted Gold",
    "ENCHANTED_RAW_CHICKEN": "Enchanted Raw Chicken",
    "ENCHANTED_WATER_LILY": "Enchanted Lily Pad",
    "LOG:1": "Spruce Wood",
    "TITANIUM_ORE": "Titanium",
    "BLUE_SHARK_TOOTH": "Blue Shark Tooth",
    "CATALYST": "Catalyst",
    "LOG:3": "Jungle Wood",
    "LOG:2": "Birch Wood",
    "BLESSED_BAIT": "Blessed Bait",
    "ENCHANTED_GLOWSTONE_DUST": "Enchanted Glowstone Dust",
    "ENCHANTED_INK_SACK": "Enchanted Ink Sack",
    "ENCHANTED_CACTUS": "Enchanted Cactus",
    "ENCHANTED_SUGAR_CANE": "Enchanted Sugar Cane",
    "ENCHANTED_COOKED_SALMON": "Enchanted Cooked Salmon",
    "ENCHANTED_SEEDS": "Enchanted Seeds",
    "LOG": "Oak Wood",
    "JACOBS_TICKET": "Jacob's Ticket",
    "ENCHANTED_BONE_BLOCK": "Enchanted Bone Block",
    "GHAST_TEAR": "Ghast Tear",
    "UNSTABLE_FRAGMENT": "Unstable Dragon Fragment",
    "ENCHANTED_ENDER_PEARL": "Enchanted Ender Pearl",
    "PURPLE_CANDY": "Purple Candy",
    "ENCHANTED_FERMENTED_SPIDER_EYE": "Enchanted Fermented Spider Eye",
    "POLISHED_PUMPKIN": "Polished Pumpkin",
    "SPIKED_BAIT": "Spiked Bait",
    "ENCHANTED_GOLD_BLOCK": "Enchanted Gold Block",
    "ENCHANTED_JUNGLE_LOG": "Enchanted Jungle Wood",
    "ENCHANTED_FLINT": "Enchanted Flint",
    "IRON_INGOT": "Iron Ingot",
    "ENCHANTED_EMERALD_BLOCK": "Enchanted Emerald Block",
    "ENCHANTED_CLAY_BALL": "Enchanted Clay",
    "GLOWSTONE_DUST": "Glowstone Dust",
    "GOLD_INGOT": "Gold Ingot",
    "REVENANT_VISCERA": "Revenant Viscera",
    "TARANTULA_SILK": "Tarantula Silk",
    "TITANIC_EXP_BOTTLE": "Titanic Experience Bottle",
    "ENCHANTED_MUTTON": "Enchanted Mutton",
    "SUPER_COMPACTOR_3000": "Super Compactor 3000",
    "SUPER_EGG": "Super Enchanted Egg",
    "ENCHANTED_IRON": "Enchanted Iron",
    "STOCK_OF_STONKS": "Stock of Stonks",
    "MITHRIL_ORE": "Mithril",
    "ENCHANTED_HAY_BLOCK": "Enchanted Hay Bale",
    "ENCHANTED_PAPER": "Enchanted Paper",
    "ENCHANTED_TITANIUM": "Enchanted Titanium",
    "ENCHANTED_BONE": "Enchanted Bone",
    "ENCHANTED_DIAMOND_BLOCK": "Enchanted Diamond Block",
    "SPOOKY_BAIT": "Spooky Bait",
    "SUPERIOR_FRAGMENT": "Superior Dragon Fragment",
    "EMERALD": "Emerald",
    "ENCHANTED_RABBIT_FOOT": "Enchanted Rabbit Foot",
    "LIGHT_BAIT": "Light Bait",
    "HOT_POTATO_BOOK": "Hot Potato Book",
    "ENCHANTED_ICE": "Enchanted Ice",
    "CLAY_BALL": "Clay",
    "OLD_FRAGMENT": "Old Dragon Fragment",
    "GREEN_GIFT": "Green Gift",
    "PACKED_ICE": "Packed Ice",
    "WATER_LILY": "Lily Pad",
    "LOG_2": "Acacia Wood",
    "HAMSTER_WHEEL": "Hamster Wheel",
    "ENCHANTED_OBSIDIAN": "Enchanted Obsidian",
    "ENCHANTED_COAL": "Enchanted Coal",
    "ENCHANTED_QUARTZ": "Enchanted Quartz",
    "COAL": "Coal",
    "ENDER_PEARL": "Ender Pearl",
    "ENCHANTED_COAL_BLOCK": "Enchanted Block of Coal",
    "WEREWOLF_SKIN": "Werewolf Skin",
    "ENCHANTED_PRISMARINE_CRYSTALS": "Enchanted Prismarine Crystals",
    "DAEDALUS_STICK": "Daedalus Stick",
    "ENCHANTED_WET_SPONGE": "Enchanted Wet Sponge",
    "ENCHANTED_RAW_FISH": "Enchanted Raw Fish",
    "ENDER_STONE": "End Stone",
    "QUARTZ": "Nether Quartz",
    "FOUL_FLESH": "Foul Flesh",
    "RAW_BEEF": "Raw Beef",
    "JERRY_BOX_PURPLE": "Purple Jerry Box",
    "ENCHANTED_EYE_OF_ENDER": "Enchanted Eye of Ender",
    "ECTOPLASM": "Ectoplasm",
    "SUGAR_CANE": "Sugar Cane",
    "MAGMA_CREAM": "Magma Cream",
    "SHARK_BAIT": "Shark Bait",
    "RED_GIFT": "Red Gift",
    "ENCHANTED_MITHRIL": "Enchanted Mithril",
    "JERRY_BOX_BLUE": "Blue Jerry Box",
    "ENCHANTED_RAW_BEEF": "Enchanted Raw Beef",
    "ENCHANTED_FEATHER": "Enchanted Feather",
    "ENCHANTED_SLIME_BLOCK": "Enchanted Slime Block",
    "ENCHANTED_OAK_LOG": "Enchanted Oak Wood",
    "RABBIT_HIDE": "Rabbit Hide",
    "WHITE_GIFT": "White Gift",
    "RABBIT": "Raw Rabbit",
    "SULPHUR": "Gunpowder",
    "DARK_BAIT": "Dark Bait",
    "NETHER_STALK": "Nether Wart",
    "ENCHANTED_CARROT": "Enchanted Carrot",
    "ENCHANTED_PUMPKIN": "Enchanted Pumpkin",
    "GRIFFIN_FEATHER": "Griffin Feather",
    "ROTTEN_FLESH": "Rotten Flesh",
    "ENCHANTED_COOKED_FISH": "Enchanted Cooked Fish",
    "OBSIDIAN": "Obsidian",
    "MINNOW_BAIT": "Minnow Bait",
    "ENCHANTED_MAGMA_CREAM": "Enchanted Magma Cream",
    "ENCHANTED_FIREWORK_ROCKET": "Enchanted Firework Rocket",
    "STARFALL": "Starfall",
    "LEATHER": "Leather",
    "ENCHANTED_COOKED_MUTTON": "Enchanted Cooked Mutton",
    "REFINED_TITANIUM": "Refined Titanium",
    "ENCHANTED_RABBIT": "Enchanted Raw Rabbit",
    "MUTANT_NETHER_STALK": "Mutant Nether Wart",
    "ENCHANTED_BREAD": "Enchanted Bread",
    "FUMING_POTATO_BOOK": "Fuming Potato Book",
    "ENCHANTED_CHARCOAL": "Enchanted Charcoal",
    "ENCHANTED_BLAZE_POWDER": "Enchanted Blaze Powder",
    "SUMMONING_EYE": "Summoning Eye",
    "FISH_BAIT": "Fish Bait",
    "SNOW_BLOCK": "Snow Block",
    "ENCHANTED_BAKED_POTATO": "Enchanted Baked Potato",
    "COMPACTOR": "Compactor",
    "ENCHANTED_DIAMOND": "Enchanted Diamond"
}