
name: Auto Restart on git push

on:
  push:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: # Set the secret as an input
          API_KEY: ${{ secrets.SWEPLOX_APPI_KEY }}
      - name: run1
        run: curl "https://my.panel.url/api/client/servers/c640750b/power" -H "Content-Type: application/json" -H "Accept: application/vnd.wisp.v1+json" -H "Authorization: Bearer ${{API_KEY}}" -X POST -d '{"signal": "kill"}'
      
