name: Auto Restart on git push

on:
  push:
    branches: [ stable ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          API_KEY: ${{ secrets.SWEPLOX_API_KEY }}
        run: "curl -sSL https://raw.githubusercontent.com/EclipseDiscordBot/EclipseDiscordBot/master/scripts/restart.bash | bash"
      
