name: Auto Increment version based on

on:
  push:
    branches: [ master ]


jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: "curl -sSL https://raw.githubusercontent.com/EclipseDiscordBot/EclipseDiscordBot/master/scripts/inc_version.bash | bash"
        env:
          author: ${{ github.event.push.user.login }}